export const FETCH_USER_APP = 'FETCH_USER_APP';

export const SET_USER_ROLES = 'SET_USER_ROLES';

export const REGISTER_USER = {
  request: 'REGISTER_USER_REQUEST',
  success: 'REGISTER_USER_SUCCESS',
  error: 'REGISTER_USER_ERROR',
};

export const SET_FETCHED_SERVICES = 'SET_FETCHED_SERVICES';

export const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE';

export const SET_FILTER_LIST_CLIENTS = 'SET_FILTER_LIST_CLIENTS';

export const SET_EDIT_MODE_CLIENT_ROW = 'SET_EDIT_MODE_CLIENT_ROW';

export const SET_EDIT_MODE_ALL_CLIENT_ROWS = 'SET_EDIT_MODE_ALL_CLIENT_ROWS';

export const FETCH_CLIENTS = {
  request: 'FETCH_CLIENTS_REQUEST',
  success: 'FETCH_CLIENTS_SUCCESS',
  error: 'FETCH_CLIENTS_ERROR',
};

export const FETCH_SERVICES = {
  request: 'FETCH_SERVICES_REQUEST',
  success: 'FETCH_SERVICES_SUCCESS',
  error: 'FETCH_SERVICES_ERROR',
};

export const FETCH_SUBSCRIPTION_DETAILS = {
  request: 'FETCH_SUBSCRIPTION_DETAILS_REQUEST',
  success: 'FETCH_SUBSCRIPTION_DETAILS_SUCCESS',
  error: 'FETCH_SUBSCRIPTION_DETAILS_ERROR',
};
