export const FETCH_CUSTOMER_FAMILY_SUMMARY = {
  request: 'FETCH_CUSTOMER_FAMILY_SUMMARY_REQUEST',
  success: 'FETCH_CUSTOMER_FAMILY_SUMMARY_SUCCESS',
  error: 'FETCH_CUSTOMER_FAMILY_SUMMARY_ERROR',
};

export const FETCH_CUSTOMER_COMPANY_SUMMARY = {
  request: 'FETCH_CUSTOMER_COMPANY_SUMMARY_REQUEST',
  success: 'FETCH_CUSTOMER_COMPANY_SUMMARY_SUCCESS',
  error: 'FETCH_CUSTOMER_COMPANY_SUMMARY_ERROR',
};

export const FETCH_CUSTOMER_DELIVERY_ORDERS = {
  request: 'FETCH_CUSTOMER_DELIVERY_ORDERS_REQUEST',
  success: 'FETCH_CUSTOMER_DELIVERY_ORDERS_SUCCESS',
  error: 'FETCH_CUSTOMER_DELIVERY_ORDERS_ERROR',
};

export const FETCH_CUSTOMER_PROFILE = {
  request: 'FETCH_CUSTOMER_PROFILE_REQUEST',
  success: 'FETCH_CUSTOMER_PROFILE_SUCCESS',
  error: 'FETCH_CUSTOMER_PROFILE_ERROR',
};
